apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notification-service.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "notification-service.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "-5"
type: Opaque
data:
  username: {{ .Values.postgresql.global.postgresql.auth.username | b64enc | quote }}
  password: {{ .Values.postgresql.global.postgresql.auth.password | b64enc | quote }}
